version: '3'
services:
################ BLOCK 1 ##################
  slave_1_1:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_1_1
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_1:
        ipv4_address: 10.1.0.11

  slave_1_2:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_1_2
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_1:
        ipv4_address: 10.1.0.12


  slave_1_3:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_1_3
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_1:
        ipv4_address: 10.1.0.13


  slave_1_4:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_1_4
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_1:
        ipv4_address: 10.1.0.14


  master_1_1:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: master_1_1
    environment:
      NODE_TYPE: MASTER
    networks:
      lan_1:
        ipv4_address: 10.1.0.10



 
################ BLOCK 2 ##################
  slave_2_2:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_2_2
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_1:
        ipv4_address: 10.2.0.11


  slave_2_2:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_2_2
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_2:
        ipv4_address: 10.2.0.12


  slave_2_3:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_2_3
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_2:
        ipv4_address: 10.2.0.13


  slave_2_4:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_2_4
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_2:
        ipv4_address: 10.2.0.14


  master_2_1:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: master_2_1
    environment:
      NODE_TYPE: MASTER
    networks:
      lan_2:
        ipv4_address: 10.2.0.10



 
################ BLOCK 3 ##################
  slave_3_1:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_3_1
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_3:
        ipv4_address: 10.3.0.11


  slave_3_1:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_3_1
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_3:
        ipv4_address: 10.3.0.12


  slave_3_3:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_3_3
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_3:
        ipv4_address: 10.3.0.13


  slave_3_4:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_3_4
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_3:
        ipv4_address: 10.3.0.14


  master_3_1:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: master_3_1
    environment:
      NODE_TYPE: MASTER
    networks:
      lan_3:
        ipv4_address: 10.3.0.10



 
################ BLOCK 4 ##################
  slave_4_1:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_4_1
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_4:
        ipv4_address: 10.4.0.11


  slave_4_2:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_4_2
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_4:
        ipv4_address: 10.4.0.12


  slave_4_3:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_4_3
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_4:
        ipv4_address: 10.4.0.13


  slave_4_4:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: slave_4_4
    environment:
      NODE_TYPE: SLAVE
    networks:
      lan_4:
        ipv4_address: 10.4.0.14


  master_4_1:
    build:
      dockerfile: DockerfileNode
      context: .
    image: internship_node
    hostname: master_4_1
    environment:
      NODE_TYPE: MASTER
    networks:
      lan_4:
        ipv4_address: 10.4.0.10



 

  jenkins:
    build:
      dockerfile: DockerfileJenkins
      context: .
    image: jenkins_tester
    hostname: myjenkins
    volumes: 
    - /home/student/jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /root/.docker/config.json:/home/jenkins/.docker/config.json
    dns:
       - "8.8.8.8"
       - "4.4.4.4"
    ports:
    - '50000:50000'
    - '8080:8080'
    environment:
    - 'HTTP_PROXY="http://172.31.0.3:8000"'
    - 'HTTPS_PROXY="http://172.31.0.3:8000"'
    - 'JAVA_OPTS="-Dhttp.proxyHost=172.31.0.3 -Dhttp.proxyPort=8000 -Dhttps.proxyHost=172.31.0.3 -Dhttps.proxyPort=8000"'
    networks:
      lan_1:
        ipv4_address: 10.1.0.2
      lan_2:
        ipv4_address: 10.2.0.2
      lan_3:
        ipv4_address: 10.3.0.2
      lan_4:
        ipv4_address: 10.4.0.2
      

networks:
  lan_1:
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/24
    driver: bridge
    internal: false

  lan_2:
    ipam:
      driver: default
      config:
      - subnet: 10.2.0.0/24
    driver: bridge
    internal: false

  lan_3:
    ipam:
      driver: default
      config:
      - subnet: 10.3.0.0/24
    driver: bridge
    internal: false

  lan_4:
    ipam:
      driver: default
      config:
      - subnet: 10.4.0.0/24
    driver: bridge
    internal: false
